<a href="https://colab.research.google.com/github/HibaNasreen/Learn.py/blob/main/TASK_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create an 4x4 array with elements ranging from 0-15. And find the trace of the array.

In [1]:
#please type your answer below this line.
 
import numpy as np
array=np.arange(0,16).reshape(4,4)
print (array)
print (np.trace(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
30


2. Create a matrix with elements [6,1,1],[4,-2,5],[2,8,7].Now find the inverse this matrix.

In [2]:
#please type your answer below this line.
 
import numpy as np
a=np.array ([[6,1,1],[4,-2,5],[2,8,7]])
print (a)
b=np.linalg.inv(a)
print (b)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


3. Create an 3x3 array with elements ranging from 0-8. And find the norm this array.

In [3]:
#please type your answer below this line.
 
import numpy as np
a=np.arange(0,9).reshape(3,3)
print (a)
print (np.linalg.norm(a))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
14.2828568570857


4. Create a 4x4 array whose value ranging from 0-15.And find the eigenvalues and eigenvectors of this array.

In [4]:
#please type your answer below this line.
import numpy as np
a=np.arange(0,16).reshape(4,4)
print (a)
b,c=np.linalg.eigh(a)
print("Eigen value:",b)
print("Eigen vector:",c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Eigen value: [-7.88842207 -1.53094559 -0.88747289 40.30684055]
Eigen vector: [[-0.73212044  0.52341561 -0.27040675  0.34192975]
 [-0.39275551 -0.4753737   0.6686536   0.41553018]
 [ 0.095976   -0.54263343 -0.65259262  0.52005812]
 [ 0.54820742  0.45343678  0.23217543  0.6632935 ]]
