<a href="https://colab.research.google.com/github/HibaNasreen/Learn.py/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
 
import numpy as np
array= np.random.randint(10,size=(3,3))
print(array)

[[3 4 7]
 [8 4 4]
 [2 3 6]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [9]:
#please provide your answer below this line.
 
import numpy as np
array1= np.random.randint(10,size=(4,4))
print(array1)
array2=np.random.randint(10,size=(4,4))
print(array2)
a=array1.reshape(2,8)
b=array2.reshape(2,8)
print (np.vstack((a,b)))
print (np.hstack((a,b)))

[[3 7 3 4]
 [4 5 7 3]
 [2 4 9 2]
 [7 3 8 3]]
[[4 0 0 0]
 [2 4 9 8]
 [5 8 7 3]
 [1 5 9 7]]
[[3 7 3 4 4 5 7 3]
 [2 4 9 2 7 3 8 3]
 [4 0 0 0 2 4 9 8]
 [5 8 7 3 1 5 9 7]]
[[3 7 3 4 4 5 7 3 4 0 0 0 2 4 9 8]
 [2 4 9 2 7 3 8 3 5 8 7 3 1 5 9 7]]
