<a href="https://colab.research.google.com/github/HibaNasreen/Learn.py/blob/main/TASK_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate two  3 x 3 matrix and find it's dot product and take the transpose of the answer.

In [2]:
#please provide your answer below this line.
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)
b=np.arange(5,14).reshape(3,3)
print(b)
c=np.dot(a,b)
print(c)
print (c.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
[[ 30  33  36]
 [102 114 126]
 [174 195 216]]
[[ 30 102 174]
 [ 33 114 195]
 [ 36 126 216]]


2. Create a 3x3 matrix with elements [55,25,15], [30,44,2], [11,45,77] . Now find the determinant of the given matrix.

In [1]:
#please provide your answer below this line.
 
import numpy as np
a=np.array([[55,25,15],[30,44,2],[11,45,77]])
print (a)
b=round(np.linalg.det(a))
print (b)

[[55 25 15]
 [30 44  2]
 [11 45 77]]
137180
